// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Domain;

namespace Shop.Domain.Migrations
{
    [DbContext(typeof(AeDbContext))]
    [Migration("20181204073650_Update_more_tables")]
    partial class Update_more_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .HasColumnName("Image")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnName("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CouponCode")
                        .HasColumnName("CouponCode")
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("DiscountActiveTypeId")
                        .HasColumnName("DiscountActiveTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountRedeemTypeId")
                        .HasColumnName("DiscountRedeemTypeId")
                        .HasColumnType("int");

                    b.Property<double?>("DiscountValue")
                        .HasColumnName("DiscountValue")
                        .HasColumnType("float");

                    b.Property<string>("DisplayName")
                        .HasColumnName("DisplayName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ExpriredTime")
                        .HasColumnName("ExpriredTime")
                        .HasColumnType("int");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<double?>("MaximumDiscount")
                        .HasColumnName("MaximumDiscount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StartedTime")
                        .HasColumnName("StartedTime")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountActiveTypeId");

                    b.HasIndex("DiscountRedeemTypeId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Shop.Domain.Entities.DiscountActiveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountActiveTypes");
                });

            modelBuilder.Entity("Shop.Domain.Entities.DiscountRedeemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountRedeemTypes");
                });

            modelBuilder.Entity("Shop.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnName("Location")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillingAddress")
                        .HasColumnName("BillingAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GrandTotal")
                        .HasColumnName("GrandTotal")
                        .HasColumnType("float");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<bool?>("IsVerify")
                        .HasColumnName("IsVerify")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .HasColumnName("OrderCode")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("OrderStatusTypeId")
                        .IsRequired()
                        .HasColumnName("Status")
                        .HasColumnType("int");

                    b.Property<double?>("PackageHeight")
                        .HasColumnName("PackageHeight")
                        .HasColumnType("float");

                    b.Property<double?>("PackageLength")
                        .HasColumnName("PackageLength")
                        .HasColumnType("float");

                    b.Property<double?>("PackageWidth")
                        .HasColumnName("PackageWidth")
                        .HasColumnType("float");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnName("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasColumnName("ShippingAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("SubTotal")
                        .HasColumnName("SubTotal")
                        .HasColumnType("float");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusTypeId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnName("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnName("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnName("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingId")
                        .HasColumnName("ShippingId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShippingId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Shop.Domain.Entities.OrderStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt");

                    b.Property<string>("Name");

                    b.Property<int>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusType");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Detail")
                        .HasColumnName("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnName("Image")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescriptions")
                        .HasColumnName("MetaDescriptions")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaKeywords")
                        .HasColumnName("MetaKeywords")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaTitle")
                        .HasColumnName("MetaTitle")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PostCategoryId");

                    b.Property<int?>("PostStatusTypeId")
                        .HasColumnName("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCount")
                        .HasColumnName("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostCategoryId");

                    b.HasIndex("PostStatusTypeId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Shop.Domain.Entities.PostCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DisplayOrder")
                        .HasColumnName("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescriptions")
                        .HasColumnName("MetaDescriptions")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaKeywords")
                        .HasColumnName("MetaKeywords")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaTitle")
                        .HasColumnName("MetaTitle")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ParentId")
                        .HasColumnName("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SeoTitle")
                        .HasColumnName("SeoTitle")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("ShowOnHome")
                        .HasColumnName("ShowOnHome")
                        .HasColumnType("bit");

                    b.Property<bool?>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("Shop.Domain.Entities.PostStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PostStatusTypes");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Detail")
                        .HasColumnName("Detail")
                        .HasColumnType("text");

                    b.Property<int?>("DiscountId")
                        .HasColumnName("DiscountId")
                        .HasColumnType("int");

                    b.Property<double?>("Height")
                        .HasColumnName("Height")
                        .HasColumnType("float");

                    b.Property<string>("Image1")
                        .HasColumnName("Image1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Image2")
                        .HasColumnName("Image2")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Image3")
                        .HasColumnName("Image3")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Image4")
                        .HasColumnName("Image4")
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IncludeVAT")
                        .HasColumnName("IncludeVAT")
                        .HasColumnType("bit");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<double?>("Length")
                        .HasColumnName("Length")
                        .HasColumnType("float");

                    b.Property<string>("MetaDescriptions")
                        .HasColumnName("MetaDescriptions")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetaKeywords")
                        .HasColumnName("MetaKeywords")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetaTitle")
                        .HasColumnName("MetaTitle")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductImage")
                        .HasColumnName("ProductImage")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProductStatusTypeId")
                        .HasColumnName("ProductStatusTypeId")
                        .HasColumnType("int");

                    b.Property<double?>("PromotionPrice")
                        .HasColumnName("PromotionPrice")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnName("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("RegularPrice")
                        .HasColumnName("RegularPrice")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .HasColumnName("Sku")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCounts")
                        .HasColumnName("ViewCounts")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .HasColumnName("Warranty")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnName("Weight")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnName("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ProductStatusTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shop.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnName("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnName("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Shop.Domain.Entities.ProductStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductStatusTypes");

                    b.HasData(
                        new { Id = 1, InsertedAt = 1543909009, Name = "Out of stock", UpdatedAt = 1543909009 },
                        new { Id = 2, InsertedAt = 1543909009, Name = "Stock", UpdatedAt = 1543909009 }
                    );
                });

            modelBuilder.Entity("Shop.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderId")
                        .HasColumnName("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingCode")
                        .HasColumnName("ShippingCode")
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("ShippingPrice")
                        .HasColumnName("ShippingPrice")
                        .HasColumnType("float");

                    b.Property<string>("ShippingStatus")
                        .HasColumnName("ShippingStatus")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("Shop.Domain.Entities.ShippingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShippingProviders");
                });

            modelBuilder.Entity("Shop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnName("PasswordHash")
                        .HasColumnType("binary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnName("PasswordSalt")
                        .HasColumnType("binary(128)");

                    b.Property<string>("Phone")
                        .HasColumnName("Phone")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnName("UserName")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserStatusTypeId")
                        .HasColumnName("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserStatusTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop.Domain.Entities.UserStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserStatusTypes");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DistrictId")
                        .HasColumnName("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("InsertedAt")
                        .HasColumnName("InsertedAt")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnName("Location")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Category", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Discount", b =>
                {
                    b.HasOne("Shop.Domain.Entities.DiscountActiveType", "DiscountActiveType")
                        .WithMany("Discounts")
                        .HasForeignKey("DiscountActiveTypeId");

                    b.HasOne("Shop.Domain.Entities.DiscountRedeemType", "DiscountRedeemType")
                        .WithMany("Discounts")
                        .HasForeignKey("DiscountRedeemTypeId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.District", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shop.Domain.Entities.OrderStatusType", "OrderStatusType")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop.Domain.Entities.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("Shop.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId");

                    b.HasOne("Shop.Domain.Entities.Shipping", "Shipping")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ShippingId");

                    b.HasOne("Shop.Domain.Entities.User", "User")
                        .WithMany("OrderDetails")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Post", b =>
                {
                    b.HasOne("Shop.Domain.Entities.PostCategory")
                        .WithMany("Posts")
                        .HasForeignKey("PostCategoryId");

                    b.HasOne("Shop.Domain.Entities.PostStatusType", "PostStatusType")
                        .WithMany("Posts")
                        .HasForeignKey("PostStatusTypeId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.PostCategory", b =>
                {
                    b.HasOne("Shop.Domain.Entities.PostCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Product", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Discount", "Discount")
                        .WithMany("Products")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Shop.Domain.Entities.ProductStatusType", "ProductStatusType")
                        .WithMany("Products")
                        .HasForeignKey("ProductStatusTypeId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Shop.Domain.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Shipping", b =>
                {
                    b.HasOne("Shop.Domain.Entities.ShippingProvider", "Provider")
                        .WithMany("Shippings")
                        .HasForeignKey("ProviderId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.User", b =>
                {
                    b.HasOne("Shop.Domain.Entities.UserStatusType", "UserStatusType")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusTypeId");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Ward", b =>
                {
                    b.HasOne("Shop.Domain.Entities.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId");
                });
#pragma warning restore 612, 618
        }
    }
}
